-- Query Name: ASNFileBoeing2
-- Type: Select
-- Date Exported: 2/21/2026 9:53:55 AM
-- ----------------------------------------------------------------------

SELECT "ASN" AS CTL01, Trim([SupplierCode]) & Right(Trim([DispatchNote]),10) & Format(Date(),'yyyymmdd') & Format(Time(),'hhnnss') & "00" AS CTL02, Trim([SupplierMPID]) AS CTL03, Trim([BuyerMPID]) AS CTL04, "BSCPASNFF1" AS CTL05, "CASSAPBBGS" AS CTL06, Format(Date(),"yyyymmdd") AS CTL07, Format(Time(),'hhnnss') & "00" AS CTL08, "" AS CTL09, "" AS CTL10, "" AS CTL11, "" AS CTL12, "" AS CTL13, "Original" AS HDR01, Right(Trim([DispatchNote]),10) AS HDR02, Format([DateShip],'yyyymmdd') AS HDR03, Format([DateArrive],'yyyymmdd') AS HDR04, IIf([Carrier]="FEDEX AIR","Air","Motor-CommonCarrier") AS HDR05, Trim([Carrier]) AS HDR06, Trim([SCAC]) AS HDR07, "1" AS HDR08, "UN623351603" & Right(Trim([DispatchNote]),10) AS HDR09, Right(Trim([DispatchNote]),10) AS HDR10, Trim([BillOfLading]) AS HDR11, "" AS HDR12, Trim([WarehouseCode]) AS HDR13, Trim([SupplierCode]) AS HDR14, Trim([BuyerMPID]) AS HDR15, Trim([SupplierMPID]) AS HDR16, Format([NoBoxTotal],'000') AS HDR17, Trim([TotalWt]) AS HDR18, "LB" AS HDR19, "" AS HDR20, Trim([Name]) AS HDR21, "" AS HDR22, Trim([ShipToAddr1]) AS HDR23, Trim([ShipToAddr2]) AS HDR24, Trim([ShipToAddr3]) AS HDR25, "" AS HDR26, Trim([ShipToCity]) AS HDR27, Trim([ShipToState]) AS HDR28, "USA" AS HDR29, Trim([ShipToPostalCode]) AS HDR30, "" AS HDR31, "" AS HDR32, "" AS HDR33, "" AS HDR34, "" AS HDR35, "0010" AS DTL01, Trim([StockCode]) AS DTL02, Trim([PO]) AS DTL03, Trim([POLine]) AS DTL04, "1" AS DTL05, Trim([ShipQty]) AS DTL06, Trim([Uom]) AS DTL07, Trim([BoeingISA]) AS DTL08, "" AS DTL09, "" AS DTL10, "" AS DTL11, "" AS DTL12, "" AS DTL13, "" AS DTL14, "" AS DTL15, "" AS DTL16, "" AS DTL17, "" AS DTL18, "" AS DTL19, "" AS DTL20, "" AS DTL21, TblShippingRecords.DateShip, TblShippingRecords.ASN, TblShippingRecords.ASNSent, TblShippingRecords.ASNSentDateTime, TblShippingRecords.Hold, [TblAIC-Boeing].ASNLblName, [TblAIC-Boeing].ASN2
FROM TblShippingRecords INNER JOIN [TblAIC-Boeing] ON TblShippingRecords.Customer = [TblAIC-Boeing].Customer
WHERE (((TblShippingRecords.ASN)=True) AND ((TblShippingRecords.ASNSent)=False) AND ((TblShippingRecords.Hold)=False) AND (([TblAIC-Boeing].ASN2)="Y"));

