-- Query Name: QryPrintPackingSlip
-- Type: Select
-- Date Exported: 2/21/2026 9:53:56 AM
-- ----------------------------------------------------------------------

SELECT TblShippingRecords.DispatchNote, TblShippingRecords.Customer, TblShippingRecords.ShipTo, TblShippingRecords.ShipToAddr1, TblShippingRecords.ShipToAddr2, TblShippingRecords.ShipToAddr3, TblShippingRecords.ShipToCity, TblShippingRecords.ShipToState, TblShippingRecords.ShipToPostalCode, TblShippingRecords.SoldTo, TblShippingRecords.SoldToAddr1, TblShippingRecords.SoldToAddr2, TblShippingRecords.SoldToAddr3, TblShippingRecords.SoldToCity, TblShippingRecords.SoldToState, TblShippingRecords.SoldToPostalCode, TblShippingRecords.PO, TblShippingRecords.Terms, TblShippingRecords.ShipVia, TblShippingRecords.OrderQty, TblShippingRecords.ShipQty, TblShippingRecords.StockCode, TblShippingRecords.StockCodeDes, TblShippingRecords.Uom, TblShippingRecords.Lot, TblShippingRecords.RoyalCode, " - " & [Qty1] & " " & [Uom] AS Line1s, " - " & [Qty2] & " " & [Uom] AS Line2s, " - " & [Qty3] & " " & [Uom] AS Line3s, " - " & [Qty4] & " " & [Uom] AS Line4s, [NoBox1] & " - " & [Type1] & [Line1s] AS Line1, IIf(IsNull([NoBox2]) Or [NoBox2]<1," ",[NoBox2] & " - " & [Type2] & [Line2s]) AS Line2, IIf(IsNull([NoBox3]) Or [NoBox3]<1," ",[NoBox3] & " - " & [Type3] & [Line3s]) AS Line3, IIf(IsNull([NoBox4]) Or [NoBox4]<1," ",[NoBox4] & " - " & [Type4] & [Line4s]) AS Line4, [NoBox1] & "-" & [Type1] & IIf([NoBox2]>0,"," & [NoBox2] & "-" & [Type2],"") & IIf([NoBox3]>0,"," & [NoBox3] & "-" & [Type3],"") & IIf([NoBox4]>0,"," & [NoBox4] & "-" & [Type4],"") AS TypeBox, TblShippingRecords.TotalWt, TblShippingRecords.SalesOrder, TblShippingRecords.NoBoxTotal, TblShippingRecords.ShippedBy, TblShippingRecords.MCustRequestDat, TblShippingRecords.BillOfLading, TblShippingRecords.ScheduleB, TblShippingRecords.ECCN, dbo_TblBoeingNote.BoeingNote
FROM TblShippingRecords LEFT JOIN dbo_TblBoeingNote ON TblShippingRecords.Customer = dbo_TblBoeingNote.Customer
WHERE (((TblShippingRecords.DispatchNote)=[Forms]![Frm7PackingSlip]![txtDispatchNote]));

