-- Query Name: QryTblPackingSlipAppend
-- Type: Unknown (64)
-- Date Exported: 2/21/2026 9:53:56 AM
-- ----------------------------------------------------------------------

INSERT INTO TblPackingSlip ( DispatchNote, CustomerPoNumber, Customer, DispatchName, DispatchAddress1, DispatchAddress2, DispatchAddress3, DispatchAddress4, DispatchAddress5, DispatchPostalCode, Name, SoldToAddr1, SoldToAddr2, SoldToAddr3, SoldToAddr4, SoldToAddr5, SoldPostalCode, ShipVia, SalesOrder, Description, MOrderQty, MStockQtyToShp, MStockCode, MStockDes, MCustRequestDat, StockCode, MOrderUom, Lot, UserField1, SalesOrderLine )
SELECT dbo_MdnMaster.DispatchNote, UCase([CustomerPoNumber]) AS CPoNumber, dbo_MdnMaster.Customer, dbo_MdnMaster.DispatchName, dbo_MdnMaster.DispatchAddress1, dbo_MdnMaster.DispatchAddress2, dbo_MdnMaster.DispatchAddress3, dbo_MdnMaster.DispatchAddress4, dbo_MdnMaster.DispatchAddress5, dbo_MdnMaster.DispatchPostalCode, dbo_ArCustomer.Name, dbo_ArCustomer.SoldToAddr1, dbo_ArCustomer.SoldToAddr2, dbo_ArCustomer.SoldToAddr3, dbo_ArCustomer.SoldToAddr4, dbo_ArCustomer.SoldToAddr5, dbo_ArCustomer.SoldPostalCode, Mid$(dbo_MdnMaster.ShippingInstrs,3,20) AS ShipVia, dbo_MdnMaster.SalesOrder, dbo_TblArTerms.Description, dbo_MdnDetail.MOrderQty, dbo_MdnDetail.MStockQtyToShp, dbo_MdnDetail.MStockCode, dbo_MdnDetail.MStockDes, dbo_MdnDetail.MCustRequestDat, dbo_InvMaster.StockCode, dbo_MdnDetail.MOrderUom, dbo_MdnDetailLot.Lot, IIf(IsNull([dbo_InvMaster].[UserField1]) Or Len(Trim([dbo_InvMaster].[UserField1]))<1,'',Trim([dbo_InvMaster].[Userfield1])) AS Expr1, dbo_MdnDetail.SalesOrderLine
FROM dbo_InvMaster RIGHT JOIN (dbo_MdnDetailLot RIGHT JOIN (((dbo_MdnMaster INNER JOIN dbo_ArCustomer ON dbo_MdnMaster.Customer = dbo_ArCustomer.Customer) INNER JOIN dbo_TblArTerms ON dbo_ArCustomer.TermsCode = dbo_TblArTerms.TermsCode) INNER JOIN dbo_MdnDetail ON dbo_MdnMaster.DispatchNote = dbo_MdnDetail.DispatchNote) ON dbo_MdnDetailLot.DispatchNote = dbo_MdnMaster.DispatchNote) ON dbo_InvMaster.StockCode = dbo_MdnDetail.MStockCode
WHERE (((dbo_MdnMaster.DispatchNote)=[Forms]![Frm7PackingSlip]![txtDispatchNote]) AND ((dbo_MdnDetail.MStockCode)>"00") AND ((dbo_MdnDetail.LineType)='1 ' Or (dbo_MdnDetail.LineType)='7') AND ((dbo_MdnMaster.DispatchNoteStatus) In ('5','7','9')));

