-- Query Name: Query2
-- Type: Select
-- Date Exported: 2/21/2026 9:53:56 AM
-- ----------------------------------------------------------------------

SELECT TblShippingRecords.DispatchNote, TblShippingRecords.Customer, TblShippingRecords.ShipTo, TblShippingRecords.ShipToAddr1, TblShippingRecords.ShipToAddr2, TblShippingRecords.ShipToAddr3, TblShippingRecords.ShipToCity, TblShippingRecords.ShipToState, TblShippingRecords.ShipToPostalCode, TblShippingRecords.SoldTo, TblShippingRecords.SoldToAddr1, TblShippingRecords.SoldToAddr2, TblShippingRecords.SoldToAddr3, TblShippingRecords.SoldToCity, TblShippingRecords.SoldToState, TblShippingRecords.SoldToPostalCode, TblShippingRecords.PO, TblShippingRecords.POLine, TblShippingRecords.Terms, TblShippingRecords.Carrier, TblShippingRecords.OrderQty, TblShippingRecords.ShipQty, TblShippingRecords.StockCode, TblShippingRecords.Uom, TblShippingRecords.StockCodeDes, TblShippingRecords.RoyalCode, TblShippingRecords.Lot, TblShippingRecords.TotalWt, TblShippingRecords.SalesOrder, TblShippingRecords.ShippedBy, TblShippingRecords.DateShip, TblShippingRecords.TimeShip, TblShippingRecords.DateArrive, TblShippingRecords.SCAC, TblShippingRecords.SourceAccepted, TblShippingRecords.DateCurrent, TblShippingRecords.TimeCurrent, TblShippingRecords.NoBox1, TblShippingRecords.NoBox2, TblShippingRecords.NoBox3, TblShippingRecords.NoBox4, TblShippingRecords.Type1, TblShippingRecords.Type2, TblShippingRecords.Type3, TblShippingRecords.Type4, TblShippingRecords.Qty1, TblShippingRecords.Qty2, TblShippingRecords.Qty3, TblShippingRecords.Qty4, TblShippingRecords.NoBoxTotal, TblShippingRecords.QtyTotal, TblShippingRecords.ShipVia, TblShippingRecords.LblPrinted, TblShippingRecords.LblDatePrinted, TblShippingRecords.LblReprinted, TblShippingRecords.LblDateReprinted, TblShippingRecords.ASNSent, TblShippingRecords.ASNSentDateTime, TblShippingRecords.Cancel, TblShippingRecords.DateCancelled, TblShippingRecords.BillOfLading, TblShippingRecords.Hold, TblShippingRecords.DateHeld, TblShippingRecords.ASN, TblShippingRecords.Wt1, TblShippingRecords.Wt2, TblShippingRecords.Wt3, TblShippingRecords.Wt4, TblShippingRecords.MCustRequestDat, TblShippingRecords.Revision, TblShippingRecords.TSO, TblShippingRecords.NDTestSpec, TblShippingRecords.NDTestSampleSize, TblShippingRecords.DivisionCode, TblShippingRecords.ScheduleB, TblShippingRecords.ECCN
FROM TblShippingRecords
WHERE (((TblShippingRecords.DateShip)=#10/26/2017#));

